version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn test

workflows:
  ci:
    jobs:
      - test
# VS Code Extension Version: 1.5.1
