version: 2.1

jobs:
  style:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn style
  lint:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint
  test:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
  deploy:
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run: npx surge --project ./out --domain henry-aquino.surge.sh

workflows:
  ci-cd:
    jobs:
      - lint
      - style
      - test
      - hold:
          type: approval
          requires:
            - lint
            - style
            - test
      - deploy:
          requires:
            - hold
# VS Code Extension Version: 1.5.1
